name: ghpages-updater

on:
  release:
    types:
      - published

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt install -y cmake ninja-build pandoc
      - name: Get the version
        run: |
          echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          path: ./repo
      - name: Build docs
        run: |
          cd repo
          mkdir build
          cd build
          rm -rf CMakeCache.txt && cmake -GNinja -DBUILD_DOCS=1 -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
          cd ..
          mv build/bin/PSDToolKitDocs ../docs
          git checkout --orphan gh-pages
          git rm -rf '*'
          mv ../docs/* ./
          touch .nojekyll
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m docs
          git push -f origin gh-pages
